server:
  port: 8091
spring:
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgresPlusDialect
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/annotations
    username: postgres
    password: admin
deployment:
  url: http://annotationserver.xtptzahyma.us-east-1.elasticbeanstalk.com
