server:
  port: 8091
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  messages:
    basename: validation
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/annotations
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    username:
    password:
deployment:
  url: http://annotationserver.xtptzahyma.us-east-1.elasticbeanstalk.com