server:
  port: 8090
spring:
  thymeleaf:
    cache: false
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgresPlusDialect
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mnemosyne
    username: postgres
    password: admin
